# Generated by Django 2.1.2 on 2018-12-23 13:51

from django.db import migrations, models
import django_thumbs.fields
import my_app.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='邮箱地址')),
                ('nickname', models.CharField(default='', max_length=100, verbose_name='昵称')),
                ('signature', models.CharField(default='', max_length=300, verbose_name='个性签名')),
                ('head_image', django_thumbs.fields.ImageThumbsField(sizes=({'code': 'avatar', 'resize': 'crop', 'wxh': '125x125'}, {'code': 'm', 'resize': 'scale', 'wxh': '640x480'}, {'code': '150', 'wxh': '150x150'}), upload_to=my_app.models.generate_user_filename)),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True)),
                ('movie_id', models.IntegerField()),
                ('user_email', models.EmailField(default='', max_length=255)),
                ('create_date', models.CharField(default='', max_length=255)),
                ('comment_content', models.CharField(default='', max_length=300)),
                ('comment_like_num', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('movie_name', models.CharField(default='', max_length=255)),
                ('movie_release_date', models.CharField(default='', max_length=20)),
                ('movie_release_area', models.CharField(default='', max_length=255)),
                ('movie_score', models.IntegerField(default=0)),
                ('movie_actor_list', models.CharField(default='', max_length=2000)),
                ('trailer_id', models.IntegerField()),
                ('movie_channel', models.CharField(default='', max_length=255)),
                ('movie_intro', models.CharField(default='', max_length=500)),
                ('movie_rating_num', models.IntegerField(default=0)),
                ('movie_poster_url', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('trailer_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('trailer_name', models.CharField(default='', max_length=255)),
                ('trailer_video_url', models.CharField(default='', max_length=255)),
                ('trailer_cover_url', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
