# Generated by Django 2.1.2 on 2018-12-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_auto_20181223_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('post_title', models.CharField(default='', max_length=30)),
                ('post_content', models.CharField(default='', max_length=10000)),
                ('post_time', models.DateTimeField(auto_now_add=True)),
                ('user_email', models.EmailField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('comment_id', models.IntegerField(auto_created=True, default=1, primary_key=True, serialize=False, unique=True)),
                ('post_id', models.IntegerField()),
                ('user_email', models.EmailField(default='', max_length=255)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('comment_content', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.RenameModel(
            old_name='Comment',
            new_name='MovieComment',
        ),
        migrations.RenameField(
            model_name='moviecomment',
            old_name='movie_id',
            new_name='object_id',
        ),
    ]
