# Generated by Django 2.1.3 on 2018-12-26 03:37

from django.db import migrations
import django_thumbs.fields
import my_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0007_auto_20181226_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_url',
            field=django_thumbs.fields.ImageThumbsField(default='', sizes=({'code': 'avatar', 'resize': 'crop', 'wxh': '125x125'}, {'code': 'm', 'resize': 'scale', 'wxh': '640x480'}, {'code': '150', 'wxh': '150x150'}), upload_to=my_app.models.generate_normal_filename),
        ),
    ]
