# Generated by Django 2.1.3 on 2018-12-26 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_auto_20181226_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
