# Generated by Django 2.1.3 on 2018-12-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0011_auto_20181226_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='head_image',
            field=models.CharField(default='static/images/user/default-head_img.jpg', max_length=300, verbose_name='头像'),
        ),
    ]
