# Generated by Django 2.1.3 on 2018-12-26 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0012_auto_20181226_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_url',
            field=models.CharField(default='static/images/post/00.png', max_length=1000),
        ),
    ]
